### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by friesendrywall** [toots/shine#25]
How did this come to have LGPL when the original shine seems to have been GPL?

**Comment by toots** [comment]
We started from an original import that carried a LGPL license: https://github.com/toots/shine/tree/f06c1cc3fe7d262ab1c78d8b478a3ef7fe86e048/src

Original project is still available on sourceforge.net: https://sourceforge.net/projects/libshine-fxp/ 

What is your source for the GPL license?

**Comment by toots** [comment]
Hmm. Not sure which one then. The one here: https://www.mp3-tech.org/programmer/encoding.html has LGPL as well, right?

**Comment by friesendrywall** [comment]
Well, the shine (release 0.1.4) is gpl from what I read in the COPYING file inside.  The Shine Fixed Point release would be under that?

**Comment by toots** [comment]
I'm not sure we're looking at the same file, here's mine:
```
% md5 shine.zip
MD5 (shine.zip) = 1d6a33fae4588c697f04f1b9592266fa
% head COPYING
		  GNU LIBRARY GENERAL PUBLIC LICENSE
		       Version 2, June 1991

 Copyright (C) 1991 Free Software Foundation, Inc.
    		    59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

[This is the first released version of the library GPL.  It is
 numbered 2 because it goes with version 2 of the ordinary GPL.]
```

**Comment by friesendrywall** [comment]
That is what I have.  LGPL should say LESSER GENERAL PUBLIC LICENSE , right?

**Comment by toots** [comment]
> The license was originally called the GNU Library General Public License and was first published in 1991, and adopted the version number 2 for parity with GPL version 2. The LGPL was revised in minor ways in the 2.1 point release, published in 1999, when it was renamed the GNU Lesser General Public License to reflect the FSF's position that not all libraries should use it. Version 3 of the LGPL was published in 2007 as a list of additional permissions applied to GPL version 3.

Source: https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License

:-)

**Comment by toots** [comment]
Thanks for asking, though, it's always important to check on these issues.
