### ISSUE TITLE
Wave header parser isn't generic enough

### ISSUE THREAD

**Issue by Selur** [toots/shine#30]
Would be nice if pipe support could be added to allow decoding a source with i.e. ffmpeg and then encode with shineenc:
```
ffmpeg -y -threads 8 -loglevel fatal -i "input.aac" -ac 2 -ar 48000 -acodec pcm_s16le -f wav - | shineenc -d - output.mp3
```

**Comment by toots** [comment]
That's a great idea, I'll look at it.

**Comment by toots** [comment]
However, remember that `ffmpeg` actually has built-in support for shine: https://www.ffmpeg.org/doxygen/2.8/libshine_8c.html

**Comment by toots** [comment]
Ok, didn't realize it's already in there :-)

```
% shineenc - - < /tmp/bla.wav > /tmp/bla.mp3
```
Gonna add that to the `--help` section.

**Comment by Selur** [comment]
Somehow it's not compatible with ffmpeg calling:
```
g:\Hybrid\64bit\ffmpeg.exe -y -threads 8 -loglevel fatal -i "g:\test2.0.wav" -ac 2 -ar 48000 -acodec pcm_s16le -f wav - | g:\Hybrid\64bit\shineenc.exe -d - output.mp3
```
gives me:
```
shineenc (Liquidsoap version)
Error: WAVE data chunk not found
```

**Comment by toots** [comment]
Okay, I think I know what this must be. Thanks.

**Comment by toots** [comment]
I can't find a way to reproduce, unfortunately. @Selur, any chance you could share some file to reproduce? My email is at: toots@rastageeks.org, best would be ffmpeg-generated WAV file.

**Comment by Selur** [comment]
Will send you the wav file I used in the command line I posted above,..

**Comment by vnullptr** [comment]
**FFmpeg** generated WAVE file contains a `INFO` chunk and adds some metadata. Which might be conflicting with the `shineenc` utility.

**Comment by toots** [comment]
I found the email thread from last year. We were never able to reproduce. If someone else has issues with this, please reopen and send me the details, I'd be glad to look into it.
