### ISSUE TITLE
BIG_ENDIAN problem (Error: Unknown WAVE format) 

### ISSUE THREAD

**Issue by fr0sty1** [toots/shine#34]
I am trying to encode this wave file (output from hexdump -C <filename>):

    00000000  52 49 46 46 24 e4 57 00  57 41 56 45 66 6d 74 20  |RIFF$.W.WAVEfmt |
    00000010  10 00 00 00 01 00 02 00  80 bb 00 00 00 ee 02 00  |................|
    00000020  04 00 10 00 64 61 74 61  00 e4 57 00 00 00 00 00  |....data..W.....|

This is the output from shineenc -v /tmp/sample.wav /tmp/output.mp3:
    shineenc (Liquidsoap version)
    Looking for chunk 'fmt '
    Found chunk 'fmt ', length: 268435456
    WAVE format: 256
    Error: Unknown WAVE format

I am using shine package version 3.1.0-2 from OpenWRT on a GL.iNet GL-AR150 device.

Given the output above it looks shine is not properly converting byte order when reading from the file. WAVE format is 256 instead of 1 (0x0100 vs 0x0010) and length is 0x1000 0000 instead of 0x0000 0010

**Comment by fr0sty1** [comment]
More information on the device:

```
# cat /proc/cpuinfo
system type		: Atheros AR9330 rev 1
machine			: GL.iNet GL-AR150
processor		: 0
cpu model		: MIPS 24Kc V7.4
BogoMIPS		: 265.42
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 16
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16
```

**Comment by toots** [comment]
Thanks for the report! Any chance you could try the fix?

I have note decided when I will release these changes. The `shineenc` command line is more of an example than a critical part of the code, the shared library being the most important. I'll release in the coming months though for sure. Let me know if you have a more urgent need for the fix.

**Comment by SakuraLife** [comment]
the commit `a361ef97f82b847f3421a4301c21abd8c9bdac07` that fixed this problem causes a compile error on a little endian machine. I think the `ifdef` at line 23 mismatchs the `endif` at line 227, which cause the function `wave_open` and `wave_close` are lost.  
this is the compile log at my machine:
```
libtool: link: gcc -Isrc/lib -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -DSHINE_HAVE_BSWAP_H -funroll-loops -fno-exceptions -Wall -O2 -fsigned-char -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -o .libs/shineenc src/bin/shineenc-main.o src/bin/shineenc-wave.o  ./.libs/libshine.so -lm
/usr/bin/ld: src/bin/shineenc-main.o: in function `main':
main.c:(.text.startup+0x1a0): undefined reference to `wave_open'
/usr/bin/ld: main.c:(.text.startup+0x2ec): undefined reference to `wave_close'
collect2: error: ld returned 1 exit status
make: *** [Makefile:549: shineenc] Error 1
```
